import { config } from "dotenv";
config();
export const rawgoc = process.env.GOCALERTS;
export const rawisocountries = process.env.ISOCOUNTRIES;
export const collectionname = process.env.ALERTCOLLECTION;
export const collectionadv = process.env.ADVISORYCOLLECTION;
export const atlas = process.env.DBURL;
export const appdb = process.env.DB;
export const port = process.env.PORT;
export const graphql = process.env.GRAPHQLURL;
